"""Render a LintResult to text, Markdown, or self-contained dark HTML."""

from __future__ import annotations

import html

from .linter import LintResult
from .rules import ERROR, WARN, INFO

_SYMBOL = {ERROR: "ERROR", WARN: "WARN ", INFO: "info "}


def render_text(result: LintResult) -> str:
    c = result.counts
    lines: list[str] = []
    lines.append("MCP schema lint")
    lines.append(f"tools: {result.tool_count}   errors: {c[ERROR]}   warnings: {c[WARN]}   info: {c[INFO]}")
    lines.append("")
    if not result.findings:
        lines.append("No findings. Schemas look agent-friendly.")
        return "\n".join(lines)

    current = None
    for f in result.findings:
        if f.tool != current:
            current = f.tool
            lines.append(f"{f.tool}")
        lines.append(f"  [{_SYMBOL[f.severity]}] {f.rule}: {f.message}  ({f.field})")
    lines.append("")
    lines.append(f"{result.tools_with_errors} of {result.tool_count} tools have errors.")
    return "\n".join(lines)


def render_markdown(result: LintResult) -> str:
    c = result.counts
    md: list[str] = []
    md.append("# MCP schema lint")
    md.append("")
    md.append(f"**Tools:** {result.tool_count} &nbsp; **Errors:** {c[ERROR]} &nbsp; **Warnings:** {c[WARN]} &nbsp; **Info:** {c[INFO]}")
    md.append("")
    if not result.findings:
        md.append("No findings. Schemas look agent-friendly.")
        return "\n".join(md)
    md.append("| Severity | Tool | Rule | Field | Message |")
    md.append("|---|---|---|---|---|")
    for f in result.findings:
        md.append(f"| {f.severity} | `{f.tool}` | {f.rule} | `{f.field}` | {f.message} |")
    return "\n".join(md)


def render_html(result: LintResult) -> str:
    c = result.counts
    color = {ERROR: "#ef4444", WARN: "#f59e0b", INFO: "#38bdf8"}
    rows = ""
    for f in result.findings:
        rows += (
            f"<tr><td><span class='sev' style='background:{color[f.severity]}'>{f.severity}</span></td>"
            f"<td><code>{html.escape(f.tool)}</code></td>"
            f"<td>{html.escape(f.rule)}</td>"
            f"<td>{html.escape(f.message)}</td>"
            f"<td class='field'><code>{html.escape(f.field)}</code></td></tr>"
        )
    if not rows:
        rows = "<tr><td colspan='5'>No findings. Schemas look agent-friendly.</td></tr>"

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MCP schema lint</title>
<style>
  body{{margin:0;background:#0f172a;color:#e2e8f0;font-family:-apple-system,Segoe UI,Roboto,sans-serif;line-height:1.6;}}
  .wrap{{max-width:900px;margin:0 auto;padding:32px 20px 64px;}}
  h1{{font-size:1.6rem;margin:0 0 6px;}}
  .counts span{{display:inline-block;margin-right:16px;font-size:.9rem;color:#94a3b8;}}
  .counts b{{color:#fff;}}
  table{{width:100%;border-collapse:collapse;margin:16px 0;font-size:.88rem;}}
  td,th{{padding:7px 10px;border-bottom:1px solid #334155;text-align:left;vertical-align:top;}}
  th{{color:#94a3b8;font-size:.78rem;text-transform:uppercase;}}
  .sev{{color:#0f172a;font-weight:700;border-radius:10px;padding:1px 9px;font-size:.72rem;text-transform:uppercase;}}
  .field{{color:#94a3b8;}}
  code{{background:#243349;padding:1px 6px;border-radius:5px;font-size:.85em;color:#cbd5e1;}}
</style></head><body><div class="wrap">
<h1>MCP schema lint</h1>
<div class="counts"><span>Tools: <b>{result.tool_count}</b></span><span>Errors: <b>{c[ERROR]}</b></span><span>Warnings: <b>{c[WARN]}</b></span><span>Info: <b>{c[INFO]}</b></span></div>
<table>
<tr><th>Severity</th><th>Tool</th><th>Rule</th><th>Message</th><th>Field</th></tr>
{rows}
</table>
<p class="field" style="font-size:.82rem">Generated by mcp-schema-lint. Static analysis, offline, no server calls.</p>
</div></body></html>"""
